from .employees.employee_list import employee_list
from .home import home
from .auth.logout import logout_user
from .computers.computer_list import computer_list
from .department_details.list import department_details
from .computers.computer_form import computer_form
from .computers.computer_form import computer_edit_form
from .employees.employee_list import employee_list
from .departments.list import department_list
from .employees.employee_details import employee_details
from .computers.computer_details import computer_details
from .employees.new_employee_form import add_employee_form